
import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
});

// const archivo = Archivo({
//   subsets: ["latin"],
//   display: "swap",
// });


export const metadata: Metadata = {
  title: "Agrovest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${archivo.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
